DatabaseDirectory /mnt/clamav-db

LocalSocket /tmp/clamav/clamd.sock
LocalSocketMode 660
FixStaleSocket yes
TCPSocket 3310
TCPAddr 0.0.0.0

User vefaas-clamav
PidFile /tmp/clamav/clamd.pid
TemporaryDirectory /tmp/clamav/scan
Foreground yes

LogTime yes
LogClean no
LogVerbose no

MaxThreads 2
MaxQueue 8
MaxConnectionQueueLength 16
ReadTimeout 30
CommandReadTimeout 5
SendBufTimeout 200

StreamMaxLength 30M
MaxScanTime 9000
MaxScanSize 100M
MaxFileSize 30M
MaxRecursion 16
MaxFiles 10000

SelfCheck 600
ConcurrentDatabaseReload no
ExitOnOOM yes

EnableShutdownCommand no
EnableReloadCommand no
EnableStatsCommand no
EnableVersionCommand yes

ScanArchive yes
AlertBrokenExecutables yes
AlertExceedsMax yes
Bytecode yes
