DatabaseDirectory /mnt/clamav-db
DatabaseOwner vefaas-clamav
PidFile /tmp/clamav/freshclam.pid

DatabaseMirror database.clamav.net
Checks 1
MaxAttempts 3
ConnectTimeout 30
ReceiveTimeout 60
TestDatabases yes

OnUpdateExecute /usr/local/bin/reload-clamd
