"""initial alpha schema

Revision ID: 35f310b7eb14
Revises:
Create Date: 2026-08-30 02:05:30.934356
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '35f310b7eb14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('area_sqm', sa.Integer(), nullable=False),
    sa.Column('area_basis', sa.String(length=20), nullable=False),
    sa.Column('renovation_type', sa.String(length=20), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('fund_limit_cents', sa.Integer(), nullable=False),
    sa.Column('reserve_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('amount_delta_cents', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_table('baseline_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=80), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baseline_versions_project_id'), 'baseline_versions', ['project_id'], unique=False)
    op.create_table('change_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('proposer', sa.String(length=80), nullable=False),
    sa.Column('proposed_on', sa.Date(), nullable=False),
    sa.Column('schedule_impact_days', sa.Integer(), nullable=False),
    sa.Column('no_attachment_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('share_token_hash', sa.String(length=64), nullable=True),
    sa.Column('share_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_name', sa.String(length=80), nullable=True),
    sa.Column('confirmation_role', sa.String(length=80), nullable=True),
    sa.Column('confirmation_comment', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token_hash')
    )
    op.create_index(op.f('ix_change_orders_project_id'), 'change_orders', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=240), nullable=False),
    sa.Column('object_key', sa.String(length=120), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('related_type', sa.String(length=40), nullable=True),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_table('payment_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('planned_amount_cents', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('condition', sa.String(length=300), nullable=False),
    sa.Column('required_acceptance', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_milestones_project_id'), 'payment_milestones', ['project_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('original_name', sa.String(length=240), nullable=False),
    sa.Column('object_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('source_total_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_project_id'), 'quotes', ['project_id'], unique=False)
    op.create_table('acceptance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('accepted_on', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['payment_milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acceptance_records_milestone_id'), 'acceptance_records', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_acceptance_records_project_id'), 'acceptance_records', ['project_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('payee', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('controlled', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['payment_milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_milestone_id'), 'payment_records', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_payment_records_project_id'), 'payment_records', ['project_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=240), nullable=False),
    sa.Column('standard_name', sa.String(length=240), nullable=False),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('quantity_text', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('unit_price_cents', sa.Integer(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('source_location', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_project_id'), 'quote_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_quote_items_quote_id'), 'quote_items', ['quote_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_items_quote_id'), table_name='quote_items')
    op.drop_index(op.f('ix_quote_items_project_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_payment_records_project_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_milestone_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_acceptance_records_project_id'), table_name='acceptance_records')
    op.drop_index(op.f('ix_acceptance_records_milestone_id'), table_name='acceptance_records')
    op.drop_table('acceptance_records')
    op.drop_index(op.f('ix_quotes_project_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_payment_milestones_project_id'), table_name='payment_milestones')
    op.drop_table('payment_milestones')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_change_orders_project_id'), table_name='change_orders')
    op.drop_table('change_orders')
    op.drop_index(op.f('ix_baseline_versions_project_id'), table_name='baseline_versions')
    op.drop_table('baseline_versions')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('projects')
    # ### end Alembic commands ###
